jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build
        working-directory: ./docs  # Ensure this is set to the docs folder

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.0
        with:
          folder: ./docs/_site
